### User Registration
POST http://localhost:8000/api/register/
Content-Type: application/json

{
  "username": "Tanvir Hasan",
  "email": "abir190@yopmail.com",
  "password": "verysecurePassWord"
}
 
### Account Activation
POST http://localhost:8000/api/activate/
Content-Type: application/json

{
  "email": "abir19@yopmail.com",
  "pin": "600258"
}

### User Login
POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "email": "abir19@yopmail.com",
  "password": "verysecurePassWord"
}