### User Registration
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "username": "Tanvir Hasan Abir",
  "email": "bsse1321@yopmail.com",
  "password": "bsse1321@yopmail.com"
}
 
### Account Activation
POST http://localhost:8000/api/auth/activate/
Content-Type: application/json

{
  "email": "bsse1321@yopmail.com",
  "pin": "286AR5"
}

### User Login
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "bsse1321@iit.du.ac.bd",
  "password": "bsse1321@iit.du.ac.bd"
}


### User Login
GET http://localhost:8000/api/blogs/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NDA2OTc5LCJpYXQiOjE3NDQ0MDMzNzksImp0aSI6IjFjMDVmNzMwYTFjNDRkZGNiZDgwMDZhZmU0YjMyMzFlIiwidXNlcl9pZCI6NTl9.QGwHDMdOf9hv38ZEIjvKJlvALFzvrXjPuNOZaXwC2ms

### Password reset
POST http://localhost:8000/api/auth/password-reset/
Content-Type: application/json

{
  "email": "bsse1321@iit.du.ac.bd"
}

### Password reset confirmation
POST http://localhost:8000/api/auth/password-reset-confirm/
Content-Type: application/json

{
  "email": "bsse1321@iit.du.ac.bd",
  "pin":"7068R1",
  "new_password":"bsse1321@iit."
}


### Password reset confirmation
GET http://localhost:8000/api/auth/token/verify/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzU1ODE2LCJpYXQiOjE3NDQzNTIyMTYsImp0aSI6ImNiZDA3MTBiNzg3MzQxZTFiM2JjNzRhZTZjZTVjYjk5IiwidXNlcl9pZCI6NTl9.0kD5zeN3fNsrI-A7vm11deVI48GXYFndmwEuVusg-jQ

{
  "email": "bsse1321@iit.du.ac.bd",
  "pin":"IA4R1R",
  "password": "verysecurePassWord"
  
}

### logout
POST http://localhost:8000/api/auth/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0Mzk0MDIwLCJpYXQiOjE3NDQzOTA0MjAsImp0aSI6IjQyZTAwMTI3ZTNlODRjMzZiNDI5ZjFkZTc5OTM0ZGE3IiwidXNlcl9pZCI6NTl9.MVVh_hvwMlCOoCNscNHctuzcIEsoWnw-TLCx-B90Qk0

{
  "email": "farshid.kabir.23@gmail.com",
  "pin":"IA4R1R",
  "new_password":"thisisnewPassword"
}

### User Login
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "bsse1321@iit.du.ac.bd",
  "password": "bsse1321@iit.du.ac.bd"
}

### blogs creation
POST http://localhost:8000/api/blogs/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzY1MDUyLCJpYXQiOjE3NDQzNjE0NTIsImp0aSI6ImQ1MTgzNWE1MGViMjRhMTA5NzVlZjRiNjA3ODFkNzRhIiwidXNlcl9pZCI6Njl9.CNgRF5UCfc0yQZMBcbK4ceadE9zk31rnMeHlqeJCNGU

{
  "title": "My last Blog Post",
  "content": "This is the content of my last blog post.",
  "status": "draft"
}


### blog list 
GET http://localhost:8000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzY1MDUyLCJpYXQiOjE3NDQzNjE0NTIsImp0aSI6ImQ1MTgzNWE1MGViMjRhMTA5NzVlZjRiNjA3ODFkNzRhIiwidXNlcl9pZCI6Njl9.CNgRF5UCfc0yQZMBcbK4ceadE9zk31rnMeHlqeJCNGU

{
  "title": "My First Blog Post",
  "content": "This is the content of my first blog post.",
  "status": "draft"
}

### blog details 
GET http://localhost:8000/api/blogs/29/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MTM5Nzk5LCJpYXQiOjE3NDQxMzk0OTksImp0aSI6IjdmMjIxMjYwODhmNzRkYzY5N2MwODVjM2M1MDZhOTIwIiwidXNlcl9pZCI6NTl9.l_sMQASP4xCWqeFw-PAbPPoXj3loUCFZ47ViKQJxA7w

{
  "title": "My First Blog Post",
  "content": "This is the content of my first blog post.",
  "status": "draft"
}


### blog edit 
PUT http://localhost:8000/api/blogs/28/edit/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MzkxNzc4LCJpYXQiOjE3NDQzODgxNzgsImp0aSI6IjA5MTFkYjE1NzMwMTQ4N2FhMTFlNzU3ZWRkMjc5OTZlIiwidXNlcl9pZCI6NTl9.WWWmi6ZwHcql0DLYH6HLow8TNsjLl2NXSLijyBm_Tnk

{
  "title": "Updated Blog Title",
  "content": "Updated content for the blog.",
  "status": "published"
}

### blog delete 
DELETE http://localhost:8000/api/blogs/1/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzOTM1MTUzLCJpYXQiOjE3NDM5MzQ4NTMsImp0aSI6ImYyM2E4ZGM4OGE5MzQwMDY4YjI3NTQxYWZlNTAyNjUyIiwidXNlcl9pZCI6NTl9.lgnMUxHs0Vl0KbcVbyRg2Cxf_-xm06L7tvEktikuY6A

{
  "title": "Updated Blog Title",
  "content": "Updated content for the blog.",
  "status": "published"
}



### comment on blogs 
POST http://localhost:8000/api/blogs/24/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MjM0Mjc3LCJpYXQiOjE3NDQyMzA2NzcsImp0aSI6IjYwOTFiM2Q0N2MzOTQzNmViODE4ZGMxYjdiMzNjMDYxIiwidXNlcl9pZCI6NTl9.Nxv15wQumX0EFm_hzO0XFHXa3sjby9gILKmfeOqEows

{
  "content": "Great blog post!"
}
