services:
  backend:
    build: ./backend
    command: python3 blogify/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blogify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: ./backend
    command: sh -c "chmod +x run_celery.sh && ./run_celery.sh"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - backend
    env_file:
      - ./backend/.env
    restart: always

  celery-beat:
    build: ./backend
    command: sh -c "chmod +x run_celery.sh && ./run_celery.sh beat"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - backend
    env_file:
      - ./backend/.env
    restart: always

volumes:
  postgres_data:
